on:
  workflow_dispatch:
    inputs:
      dispatch_token:
        description: 'Token that authorize the dispatch'
        required: true
      head_sha:
        description: 'Head commit SHA that dispatched the workflow'
        required: true
      pr_author_username:
        description: 'Pull Request author username'
        required: true
      pr_number:
        description: 'Pull Request number that dispatched the workflow'
        required: true

jobs:
  Checkstyle-evaluator:
    runs-on: self-hosted
    name: Checkstyle
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'main'

      - name: Fetch Java Checkstyle evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/java-checkstyle-action
          ref: v1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/java-checkstyle-action

      - name: Run Java Checkstyle evaluator
        id: checkstyle-evaluator
        uses: ./.github/actions/java-checkstyle-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.inputs.pr_number }}
  Evaluator:
    runs-on: self-hosted
    needs: [Checkstyle-evaluator]
    name: Evaluator Job
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch JUnit evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/junit-evaluator-action
          ref: v1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/junit-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v4
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'main'

      - name: Run JUnit evaluation
        id: evaluator
        uses: ./.github/actions/junit-evaluator
        with:
          pr_author_username: ${{ github.event.inputs.pr_author_username }}

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.inputs.pr_number }}